/**
 * Deploy Pipeline Generator — Dockerfile + docker-compose + GitHub Actions CI/CD
 *
 * Projenin stack'ine göre otomatik deploy dosyaları üretir.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

export interface DeployConfig {
  runtime: 'node' | 'bun';
  nodeVersion: string;
  port: number;
  hasDb: boolean;
  dbType?: 'postgresql' | 'redis' | 'both';
  registry?: string; // docker registry
}

export class DeployGenerator {
  private root: string;

  constructor(projectRoot: string) {
    this.root = projectRoot;
  }

  async generate(config: DeployConfig): Promise<string[]> {
    const files: string[] = [];

    files.push(await this.writeDockerfile(config));
    files.push(await this.writeDockerignore());
    files.push(await this.writeDockerCompose(config));
    files.push(await this.writeGitHubCI(config));

    return files;
  }

  private async writeDockerfile(c: DeployConfig): Promise<string> {
    const content = `# Generated by CSNS
FROM node:${c.nodeVersion}-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --production=false
COPY . .
RUN npm run build

FROM node:${c.nodeVersion}-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
EXPOSE ${c.port}
USER node
CMD ["node", "dist/server.js"]
`;
    await writeFile(join(this.root, 'Dockerfile'), content);
    return 'Dockerfile';
  }

  private async writeDockerignore(): Promise<string> {
    const content = `node_modules
dist
.git
.env
.env.local
*.md
tests
coverage
.turbo
.next
`;
    await writeFile(join(this.root, '.dockerignore'), content);
    return '.dockerignore';
  }

  private async writeDockerCompose(c: DeployConfig): Promise<string> {
    let services = `  app:
    build: .
    ports:
      - "\${PORT:-${c.port}}:${c.port}"
    environment:
      - NODE_ENV=production
      - PORT=${c.port}`;

    if (c.hasDb && (c.dbType === 'postgresql' || c.dbType === 'both')) {
      services += `
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5`;
    }

    if (c.hasDb && (c.dbType === 'redis' || c.dbType === 'both')) {
      services += `

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s`;
    }

    let volumes = '';
    if (c.hasDb) {
      volumes = `\nvolumes:`;
      if (c.dbType === 'postgresql' || c.dbType === 'both') volumes += `\n  pgdata:`;
    }

    const content = `# Generated by CSNS
services:
${services}
${volumes}
`;
    await writeFile(join(this.root, 'docker-compose.yml'), content);
    return 'docker-compose.yml';
  }

  private async writeGitHubCI(c: DeployConfig): Promise<string> {
    await mkdir(join(this.root, '.github', 'workflows'), { recursive: true });
    const content = `# Generated by CSNS
name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${c.nodeVersion}'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${c.nodeVersion}'
          cache: 'npm'
      - run: npm ci
      - run: npx tsc --noEmit

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${c.nodeVersion}'
          cache: 'npm'
      - run: npm ci
      - run: npm audit --audit-level=high
`;
    await writeFile(join(this.root, '.github', 'workflows', 'ci.yml'), content);
    return '.github/workflows/ci.yml';
  }
}
