/**
 * Git Auto — Branch + Commit + PR creation
 */

import { execSync } from 'node:child_process';

export interface GitAutoResult {
  branch: string;
  commitHash: string;
  prUrl?: string;
}

export class GitAuto {
  private root: string;

  constructor(projectRoot: string) {
    this.root = projectRoot;
  }

  /**
   * Create branch, stage all, commit, optionally push + create PR.
   */
  async commitAndPush(message: string, options?: {
    branch?: string;
    push?: boolean;
    createPR?: boolean;
    prTitle?: string;
  }): Promise<GitAutoResult> {
    const branch = options?.branch ?? `csns/${Date.now()}`;

    // Create and switch branch
    this.exec(`git checkout -b ${branch}`);

    // Stage all changes
    this.exec('git add -A');

    // Commit
    this.exec(`git commit -m "${message.replace(/"/g, '\\"')}"`);

    // Get commit hash
    const commitHash = this.exec('git rev-parse --short HEAD').trim();

    let prUrl: string | undefined;

    if (options?.push) {
      this.exec(`git push origin ${branch}`);

      if (options.createPR) {
        try {
          const title = options.prTitle ?? message.split('\n')[0] ?? 'CSNS auto-generated changes';
          const output = this.exec(`gh pr create --title "${title.replace(/"/g, '\\"')}" --body "Auto-generated by CSNS" --head ${branch}`);
          prUrl = output.trim();
        } catch {
          // gh CLI not available
        }
      }
    }

    return { branch, commitHash, prUrl };
  }

  /**
   * Check if working tree is clean.
   */
  isClean(): boolean {
    try {
      const status = this.exec('git status --porcelain');
      return status.trim().length === 0;
    } catch {
      return true;
    }
  }

  private exec(cmd: string): string {
    return execSync(cmd, { cwd: this.root, encoding: 'utf-8', timeout: 30_000 });
  }
}
